apiVersion: v1
kind: Service              
metadata:
  name: called-lb
spec:
  type: LoadBalancer       
  ports:
  - port: 80             
    targetPort: 8081        
  selector:            
    app: called    
---
apiVersion: apps/v1 #apps/v1beta2 #extensions/v1beta2 #extensions/v1beta1
kind: Deployment
metadata:
  name: called
  labels:
    app: called
spec:
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  selector:
    matchLabels:
      app: called
      tier: caller-called
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: called
        tier: caller-called
    spec:
      containers:
      - image: alessandroargentieri/kuba-called
        name: called
        env:
        - name: CALLEDPORT
          value: "8081"
        ports:
        - containerPort: 8081
          name: called
